---

- name: Test sshd configuration and restart
  command: sshd -t
  notify: [ 'Restart sshd' ]

- name: Restart sshd
  vars:
    ssh_package: "{{ 'ssh' if ansible_distribution == 'Debian' or ansible_distribution == 'Ubuntu' else 'sshd' }}"
  service:
    name: "{{ ssh_package }}"
    state: 'restarted'
